name: Arxiv Paper Fetcher

on:
  schedule:
    - cron: '0 */4 * * *'  # 4時間ごとに実行
  workflow_dispatch:  # 手動実行用

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run paper fetcher
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: python src/main.py 
